# Deploy Theme to Store when new changes are pushed to master branch
name: Deploy Theme to Store

on:
  workflow_dispatch:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node }}

    - name: npm cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Stencil CLI Dependency
      run: npm install -g @bigcommerce/stencil-cli

    - name: Install Dependencies
      run: npm ci

    - name: Connect to store
      env:
        URL: ${{ secrets.PERF_TEST_STORE_URL }}
        TOKEN: ${{ secrets.PERF_TEST_STORE_TOKEN }}
      run: stencil init -u $URL -t $TOKEN -p 3000

    - name: Push theme live, automatically deleting oldest theme if necessary
      run: stencil push -a -d
      
    - name: Generate Lighthouse Report
      uses: justinribeiro/lighthouse-action@master
      with:
        secret: ${{ secrets.GITHUB_TOKEN }}
        url: ${{ secrets.PERF_TEST_STORE_URL }}
        wptConnectionSpeed: threegfast
    - name: Saving Lighthouse Audit Artifacts
      uses: actions/upload-artifact@master
      with:
        name: lighthouse-artifacts
        path: './results'
