# This workflow will do a clean install of your theme's dependencies and attempt to bundle the theme with Stencil CLI. 
# If the theme fails to bundle, you can review the error logs to find out why.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Screenshot

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node }}

    - name: npm cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Stencil CLI Dependency
      run: npm install -g @bigcommerce/stencil-cli

    - name: Install Theme Dependencies
      run: npm ci

    - name: Connect to store
      env:
        URL: ${{ secrets.STENCIL_STORE_URL_PRODUCTION }}
        TOKEN: ${{ secrets.STENCIL_ACCESS_TOKEN_PRODUCTION }}
      run: stencil init -u $URL -t $TOKEN -p 3000

    - name: Start CLI
      run: npx stencil start

    - name: Screenshot Website
      uses: swinton/screenshot-website@v1.x
      with:
        source: https://github.com/swinton/screenshot-website
        destination: homepage-screenshot.png
        full-page: true

    - name: Upload screenshot
      uses: actions/upload-artifact@v2
      with:
        name: Bundled Theme
        path: homepage-screenshot.png
